## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [2]:
import torch
import torch.nn as nn
from collections import OrderedDict

In [3]:
model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 2)),  
    ('Sigmoid', nn.Sigmoid()),    
    ('output', nn.Linear(2, 2)),  
    ('Sigmoid', nn.Sigmoid())
]))
print(model1)

data_in1 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in1)

data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)

criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)

for epoch in range(10000):
    outputs1 = model1(data_in1)
    loss1 = criterion1(outputs1, data_target1)
    
    optimizer1.zero_grad()  
    loss1.backward()          
    optimizer1.step()         
    
    predicted_classes1 = (outputs1.round() == data_target1)
    accuracy1 = predicted_classes1.all(dim=1).sum() / len(data_target1)
    if (epoch+1) % 1000 == 0:
        print(f'Epoch {epoch+1} Loss: {loss1.item()} Accuracy: {accuracy1*100}%')
    if accuracy1 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break

print(outputs1)
predicted1 = torch.round(outputs1)
correct1 = (predicted1 == data_target1).all(dim=1).sum()
total1 = data_target1.size(0)
accuracy1 = correct1 / total1
print(f'Model Accuracy: {accuracy1*100}%')  

    
print(f"Model weights:")
for name, param in model1.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Sequential(
  (hidden): Linear(in_features=2, out_features=2, bias=True)
  (Sigmoid): Sigmoid()
  (output): Linear(in_features=2, out_features=2, bias=True)
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Epoch 1000 Loss: 0.16116999089717865 Accuracy: 50.0%
Epoch 2000 Loss: 0.15717056393623352 Accuracy: 50.0%
Model 1 reached 100% accuracy at epoch 2647
tensor([[-0.2437,  0.4955],
        [ 0.2480,  0.5023],
        [ 0.2480,  0.5060],
        [ 0.7407,  0.5000]], grad_fn=<AddmmBackward0>)
Model Accuracy: 100.0%
Model weights:
hidden.weight tensor([[-0.5635, -0.5765],
        [ 0.7730,  0.7662]])
hidden.bias tensor([ 0.8694, -0.6875])
output.weight tensor([[-1.0284,  1.9241],
        [ 0.8254,  0.6246]])
output.bias tensor([-0.1629, -0.2950])


In [4]:
model2 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 5)),  
    ('ReLU', nn.ReLU()),    
    ('output', nn.Linear(5, 2)),  
    ('Sigmoid', nn.Sigmoid())
]))
print(model2)

data_in2 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in2)

data_target2 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target2)

criterion2 = nn.MSELoss()
optimizer2 = torch.optim.SGD(model2.parameters(), lr=0.1)

for epoch in range(10000):
    outputs2 = model2(data_in2)
    loss2 = criterion2(outputs2, data_target1)
    
    optimizer2.zero_grad()  
    loss2.backward()          
    optimizer2.step()         
    
    predicted_classes2 = (outputs2.round() == data_target2)
    accuracy2 = predicted_classes2.all(dim=1).sum() / len(data_target1)
    if (epoch+1) % 1000 == 0:
        print(f'Epoch {epoch+1} Loss: {loss2.item()} Accuracy: {accuracy2*100}%')
    if accuracy2 == 1:
        print(f"Model 2 reached 100% accuracy at epoch {epoch+1}")
        break

print(outputs2)
predicted2 = torch.round(outputs2)
correct2 = (predicted2 == data_target2).all(dim=1).sum()
total2 = data_target2.size(0)
accuracy2 = correct2 / total2
print(f'Model Accuracy: {accuracy2*100}%')  

    
print(f"Model weights:")
for name, param in model2.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Sequential(
  (hidden): Linear(in_features=2, out_features=5, bias=True)
  (ReLU): ReLU()
  (output): Linear(in_features=5, out_features=2, bias=True)
  (Sigmoid): Sigmoid()
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Epoch 1000 Loss: 0.10705627501010895 Accuracy: 75.0%
Model 2 reached 100% accuracy at epoch 1860
tensor([[0.0465, 0.3989],
        [0.0947, 0.5000],
        [0.0720, 0.8823],
        [0.9253, 0.1358]], grad_fn=<SigmoidBackward0>)
Model Accuracy: 100.0%
Model weights:
hidden.weight tensor([[ 0.3602, -0.4463],
        [ 0.4404, -0.3316],
        [ 2.0401,  1.2938],
        [ 1.5817, -1.5813],
        [ 0.0849, -0.7343]])
hidden.bias tensor([-3.6190e-01, -4.4048e-01, -1.2950e+00, -1.2371e-03,  1.2601e+00])
output.weight tensor([[-0.0602,  0.0377,  2.3861, -0.7742, -1.0422],
        [-0.4102, -0.0607, -0.8858,  1.9812, -0.5609]])
output.bias tensor([-1.7080,  0.2959])


In [5]:
model3 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 8)),  
    ('ReLU', nn.ReLU()),    
    ('output', nn.Linear(8, 2)),  
    ('tanh', nn.Tanh())
]))
print(model3)

data_in3 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in3)

data_target3 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target3)

criterion3 = nn.MSELoss()
optimizer3 = torch.optim.SGD(model3.parameters(), lr=0.1)

for epoch in range(10000):
    outputs3 = model3(data_in3)
    loss3 = criterion3(outputs3, data_target1)
    
    optimizer3.zero_grad()  
    loss3.backward()          
    optimizer3.step()         
    
    predicted_classes3 = (outputs3.round() == data_target3)
    accuracy3 = predicted_classes3.all(dim=1).sum() / len(data_target3)
    if epoch % 1000 == 0:
        print(f"Epoch {epoch+1}: {accuracy3*100}%")
    if accuracy3 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break

print(outputs3)
predicted3 = torch.round(outputs3)
correct3 = (predicted3 == data_target3).all(dim=1).sum()
total3 = data_target3.size(0)
accuracy3 = correct3 / total3
print(f'Model Accuracy: {accuracy3*100}%')  

    
print(f"Model weights:")
for name, param in model3.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Sequential(
  (hidden): Linear(in_features=2, out_features=8, bias=True)
  (ReLU): ReLU()
  (output): Linear(in_features=8, out_features=2, bias=True)
  (tanh): Tanh()
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Epoch 1: 0.0%
Model 1 reached 100% accuracy at epoch 126
tensor([[-0.1384,  0.3144],
        [ 0.2034,  0.5492],
        [ 0.2617,  0.5173],
        [ 0.5714,  0.4995]], grad_fn=<TanhBackward0>)
Model Accuracy: 100.0%
Model weights:
hidden.weight tensor([[-0.3435, -0.3412],
        [-0.4135,  0.6174],
        [ 0.7156, -0.1152],
        [-0.3396,  0.2493],
        [ 0.1276,  0.2177],
        [-0.2636, -0.2978],
        [-0.3473,  0.1683],
        [-0.6863, -0.5220]])
hidden.bias tensor([ 0.7386,  0.1780,  0.6420,  0.4687,  0.5822,  0.6065, -0.3264,  0.5246])
output.weight tensor([[-0.4893,  0.2169,  0.2820, -0.0532,  0.1843, -0.4672, -0.0102,  0.1681],
        [ 0.0896,  0.31